#!/usr/bin/env bash
# setup-configs.sh — inject KSU/SUSFS configs into defconfig
# env: KSU_TYPE, SOURCE_TYPE, DEFCONFIG (full path), KERNEL_DIR
#
# Base config (overlayfs, ZRAM, LRU_GEN, TCP, HZ, debug, etc.) is
# intentionally left to gki_defconfig + vendor fragment merges.
# This script only injects KSU/SUSFS/BBG/KPM configs per variant.
# For KSU_TYPE=none: no changes at all.
set -e

: "${KSU_TYPE:?}"
: "${SOURCE_TYPE:?}"
: "${DEFCONFIG:?}"
: "${KERNEL_DIR:?}"

if [ "$KSU_TYPE" = "ksun" ]; then
  cat >> "$DEFCONFIG" << 'CONFIGS'
CONFIG_KSU=y
CONFIG_KSU_SUSFS=y
CONFIG_KSU_SUSFS_SUS_MAP=y
CONFIG_KSU_SUSFS_SUS_PATH=y
CONFIG_KSU_SUSFS_SUS_MOUNT=y
CONFIG_KSU_SUSFS_SUS_KSTAT=y
CONFIG_KSU_SUSFS_SPOOF_UNAME=y
CONFIG_KSU_SUSFS_ENABLE_LOG=y
CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y
CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y
CONFIG_KSU_SUSFS_OPEN_REDIRECT=y
CONFIG_KSU_SUSFS_SUS_SU=y
CONFIG_BBG=y
CONFIGS

elif [ "$KSU_TYPE" = "suki" ]; then
  cat >> "$DEFCONFIG" << 'CONFIGS'
CONFIG_KSU=y
CONFIG_KSU_SUSFS=y
CONFIG_KSU_SUSFS_SUS_MAP=y
CONFIG_KSU_SUSFS_SUS_PATH=y
CONFIG_KSU_SUSFS_SUS_MOUNT=y
CONFIG_KSU_SUSFS_SUS_KSTAT=y
CONFIG_KSU_SUSFS_SPOOF_UNAME=y
CONFIG_KSU_SUSFS_ENABLE_LOG=y
CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y
CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y
CONFIG_KSU_SUSFS_OPEN_REDIRECT=y
CONFIG_KSU_SUSFS_SUS_SU=y
CONFIG_KPM=y
CONFIGS
fi

echo "[OK] setup-configs done (KSU_TYPE=$KSU_TYPE)"
